package com.lefu.model.entity;

public class CustomerFee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_fee.ID
     *
     * @mbggenerated Tue Apr 18 14:06:40 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_fee.OPTIMISTIC
     *
     * @mbggenerated Tue Apr 18 14:06:40 CST 2017
     */
    private Integer optimistic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_fee.CUSTOMER_NO
     *
     * @mbggenerated Tue Apr 18 14:06:40 CST 2017
     */
    private String customerNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_fee.CARD_TYPE
     *
     * @mbggenerated Tue Apr 18 14:06:40 CST 2017
     */
    private String cardType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_fee.FEE_TYPE
     *
     * @mbggenerated Tue Apr 18 14:06:40 CST 2017
     */
    private String feeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_fee.RATE
     *
     * @mbggenerated Tue Apr 18 14:06:40 CST 2017
     */
    private String rate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_fee.UPPER_LIMIT
     *
     * @mbggenerated Tue Apr 18 14:06:40 CST 2017
     */
    private Boolean upperLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_fee.UPPER_LIMIT_FEE
     *
     * @mbggenerated Tue Apr 18 14:06:40 CST 2017
     */
    private Integer upperLimitFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_fee.BRAND_CODE
     *
     * @mbggenerated Tue Apr 18 14:06:40 CST 2017
     */
    private String brandCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_fee.ID
     *
     * @return the value of customer_fee.ID
     *
     * @mbggenerated Tue Apr 18 14:06:40 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_fee.ID
     *
     * @param id the value for customer_fee.ID
     *
     * @mbggenerated Tue Apr 18 14:06:40 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_fee.OPTIMISTIC
     *
     * @return the value of customer_fee.OPTIMISTIC
     *
     * @mbggenerated Tue Apr 18 14:06:40 CST 2017
     */
    public Integer getOptimistic() {
        return optimistic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_fee.OPTIMISTIC
     *
     * @param optimistic the value for customer_fee.OPTIMISTIC
     *
     * @mbggenerated Tue Apr 18 14:06:40 CST 2017
     */
    public void setOptimistic(Integer optimistic) {
        this.optimistic = optimistic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_fee.CUSTOMER_NO
     *
     * @return the value of customer_fee.CUSTOMER_NO
     *
     * @mbggenerated Tue Apr 18 14:06:40 CST 2017
     */
    public String getCustomerNo() {
        return customerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_fee.CUSTOMER_NO
     *
     * @param customerNo the value for customer_fee.CUSTOMER_NO
     *
     * @mbggenerated Tue Apr 18 14:06:40 CST 2017
     */
    public void setCustomerNo(String customerNo) {
        this.customerNo = customerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_fee.CARD_TYPE
     *
     * @return the value of customer_fee.CARD_TYPE
     *
     * @mbggenerated Tue Apr 18 14:06:40 CST 2017
     */
    public String getCardType() {
        return cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_fee.CARD_TYPE
     *
     * @param cardType the value for customer_fee.CARD_TYPE
     *
     * @mbggenerated Tue Apr 18 14:06:40 CST 2017
     */
    public void setCardType(String cardType) {
        this.cardType = cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_fee.FEE_TYPE
     *
     * @return the value of customer_fee.FEE_TYPE
     *
     * @mbggenerated Tue Apr 18 14:06:40 CST 2017
     */
    public String getFeeType() {
        return feeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_fee.FEE_TYPE
     *
     * @param feeType the value for customer_fee.FEE_TYPE
     *
     * @mbggenerated Tue Apr 18 14:06:40 CST 2017
     */
    public void setFeeType(String feeType) {
        this.feeType = feeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_fee.RATE
     *
     * @return the value of customer_fee.RATE
     *
     * @mbggenerated Tue Apr 18 14:06:40 CST 2017
     */
    public String getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_fee.RATE
     *
     * @param rate the value for customer_fee.RATE
     *
     * @mbggenerated Tue Apr 18 14:06:40 CST 2017
     */
    public void setRate(String rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_fee.UPPER_LIMIT
     *
     * @return the value of customer_fee.UPPER_LIMIT
     *
     * @mbggenerated Tue Apr 18 14:06:40 CST 2017
     */
    public Boolean getUpperLimit() {
        return upperLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_fee.UPPER_LIMIT
     *
     * @param upperLimit the value for customer_fee.UPPER_LIMIT
     *
     * @mbggenerated Tue Apr 18 14:06:40 CST 2017
     */
    public void setUpperLimit(Boolean upperLimit) {
        this.upperLimit = upperLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_fee.UPPER_LIMIT_FEE
     *
     * @return the value of customer_fee.UPPER_LIMIT_FEE
     *
     * @mbggenerated Tue Apr 18 14:06:40 CST 2017
     */
    public Integer getUpperLimitFee() {
        return upperLimitFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_fee.UPPER_LIMIT_FEE
     *
     * @param upperLimitFee the value for customer_fee.UPPER_LIMIT_FEE
     *
     * @mbggenerated Tue Apr 18 14:06:40 CST 2017
     */
    public void setUpperLimitFee(Integer upperLimitFee) {
        this.upperLimitFee = upperLimitFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_fee.BRAND_CODE
     *
     * @return the value of customer_fee.BRAND_CODE
     *
     * @mbggenerated Tue Apr 18 14:06:40 CST 2017
     */
    public String getBrandCode() {
        return brandCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_fee.BRAND_CODE
     *
     * @param brandCode the value for customer_fee.BRAND_CODE
     *
     * @mbggenerated Tue Apr 18 14:06:40 CST 2017
     */
    public void setBrandCode(String brandCode) {
        this.brandCode = brandCode;
    }
}