package com.lefu.model.entity;

import java.util.Date;

public class Operator {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OPERATOR.ID
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OPERATOR.OPTIMISTIC
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    private Integer optimistic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OPERATOR.USERNAME
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OPERATOR.STATUS
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OPERATOR.PASSWORD
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OPERATOR.MAX_ERROR_TIMES
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    private Integer maxErrorTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OPERATOR.LAST_LOGIN_ERR_TIME
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    private Date lastLoginErrTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OPERATOR.MODIFY_PASSWD_CYCLE
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    private Integer modifyPasswdCycle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OPERATOR.PASSWD_MODIFY_TIME
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    private Date passwdModifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OPERATOR.ALLOW_BEGIN_TIME
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    private String allowBeginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OPERATOR.ALLOW_END_TIME
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    private String allowEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OPERATOR.OPERATOR_TYPE
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    private String operatorType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OPERATOR.REALNAME
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OPERATOR.CREATE_TIME
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OPERATOR.CREATE_OPERATOR
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    private String createOperator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OPERATOR.RELOGIN_FLAG
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    private String reloginFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OPERATOR.PASSWD_EXPIRE_TIME
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    private Date passwdExpireTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OPERATOR.PASSWD_EFFECT_TIME
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    private Date passwdEffectTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OPERATOR.TRY_TIMES
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    private Integer tryTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OPERATOR.ORG_CODE
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    private String orgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OPERATOR.STAFF_NO
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    private String staffNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OPERATOR.PHONE_NO
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    private String phoneNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OPERATOR.CUSTOMER_NO
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    private String customerNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OPERATOR.CUSTOMER_TEL
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    private String customerTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OPERATOR.AGENT_NO
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    private String agentNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OPERATOR.SECOND_AGENT_ID
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    private String secondAgentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OPERATOR.ID
     *
     * @return the value of OPERATOR.ID
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OPERATOR.ID
     *
     * @param id the value for OPERATOR.ID
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OPERATOR.OPTIMISTIC
     *
     * @return the value of OPERATOR.OPTIMISTIC
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    public Integer getOptimistic() {
        return optimistic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OPERATOR.OPTIMISTIC
     *
     * @param optimistic the value for OPERATOR.OPTIMISTIC
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    public void setOptimistic(Integer optimistic) {
        this.optimistic = optimistic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OPERATOR.USERNAME
     *
     * @return the value of OPERATOR.USERNAME
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OPERATOR.USERNAME
     *
     * @param username the value for OPERATOR.USERNAME
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OPERATOR.STATUS
     *
     * @return the value of OPERATOR.STATUS
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OPERATOR.STATUS
     *
     * @param status the value for OPERATOR.STATUS
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OPERATOR.PASSWORD
     *
     * @return the value of OPERATOR.PASSWORD
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OPERATOR.PASSWORD
     *
     * @param password the value for OPERATOR.PASSWORD
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OPERATOR.MAX_ERROR_TIMES
     *
     * @return the value of OPERATOR.MAX_ERROR_TIMES
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    public Integer getMaxErrorTimes() {
        return maxErrorTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OPERATOR.MAX_ERROR_TIMES
     *
     * @param maxErrorTimes the value for OPERATOR.MAX_ERROR_TIMES
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    public void setMaxErrorTimes(Integer maxErrorTimes) {
        this.maxErrorTimes = maxErrorTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OPERATOR.LAST_LOGIN_ERR_TIME
     *
     * @return the value of OPERATOR.LAST_LOGIN_ERR_TIME
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    public Date getLastLoginErrTime() {
        return lastLoginErrTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OPERATOR.LAST_LOGIN_ERR_TIME
     *
     * @param lastLoginErrTime the value for OPERATOR.LAST_LOGIN_ERR_TIME
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    public void setLastLoginErrTime(Date lastLoginErrTime) {
        this.lastLoginErrTime = lastLoginErrTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OPERATOR.MODIFY_PASSWD_CYCLE
     *
     * @return the value of OPERATOR.MODIFY_PASSWD_CYCLE
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    public Integer getModifyPasswdCycle() {
        return modifyPasswdCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OPERATOR.MODIFY_PASSWD_CYCLE
     *
     * @param modifyPasswdCycle the value for OPERATOR.MODIFY_PASSWD_CYCLE
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    public void setModifyPasswdCycle(Integer modifyPasswdCycle) {
        this.modifyPasswdCycle = modifyPasswdCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OPERATOR.PASSWD_MODIFY_TIME
     *
     * @return the value of OPERATOR.PASSWD_MODIFY_TIME
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    public Date getPasswdModifyTime() {
        return passwdModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OPERATOR.PASSWD_MODIFY_TIME
     *
     * @param passwdModifyTime the value for OPERATOR.PASSWD_MODIFY_TIME
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    public void setPasswdModifyTime(Date passwdModifyTime) {
        this.passwdModifyTime = passwdModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OPERATOR.ALLOW_BEGIN_TIME
     *
     * @return the value of OPERATOR.ALLOW_BEGIN_TIME
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    public String getAllowBeginTime() {
        return allowBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OPERATOR.ALLOW_BEGIN_TIME
     *
     * @param allowBeginTime the value for OPERATOR.ALLOW_BEGIN_TIME
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    public void setAllowBeginTime(String allowBeginTime) {
        this.allowBeginTime = allowBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OPERATOR.ALLOW_END_TIME
     *
     * @return the value of OPERATOR.ALLOW_END_TIME
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    public String getAllowEndTime() {
        return allowEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OPERATOR.ALLOW_END_TIME
     *
     * @param allowEndTime the value for OPERATOR.ALLOW_END_TIME
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    public void setAllowEndTime(String allowEndTime) {
        this.allowEndTime = allowEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OPERATOR.OPERATOR_TYPE
     *
     * @return the value of OPERATOR.OPERATOR_TYPE
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    public String getOperatorType() {
        return operatorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OPERATOR.OPERATOR_TYPE
     *
     * @param operatorType the value for OPERATOR.OPERATOR_TYPE
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    public void setOperatorType(String operatorType) {
        this.operatorType = operatorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OPERATOR.REALNAME
     *
     * @return the value of OPERATOR.REALNAME
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OPERATOR.REALNAME
     *
     * @param realname the value for OPERATOR.REALNAME
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    public void setRealname(String realname) {
        this.realname = realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OPERATOR.CREATE_TIME
     *
     * @return the value of OPERATOR.CREATE_TIME
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OPERATOR.CREATE_TIME
     *
     * @param createTime the value for OPERATOR.CREATE_TIME
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OPERATOR.CREATE_OPERATOR
     *
     * @return the value of OPERATOR.CREATE_OPERATOR
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    public String getCreateOperator() {
        return createOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OPERATOR.CREATE_OPERATOR
     *
     * @param createOperator the value for OPERATOR.CREATE_OPERATOR
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    public void setCreateOperator(String createOperator) {
        this.createOperator = createOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OPERATOR.RELOGIN_FLAG
     *
     * @return the value of OPERATOR.RELOGIN_FLAG
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    public String getReloginFlag() {
        return reloginFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OPERATOR.RELOGIN_FLAG
     *
     * @param reloginFlag the value for OPERATOR.RELOGIN_FLAG
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    public void setReloginFlag(String reloginFlag) {
        this.reloginFlag = reloginFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OPERATOR.PASSWD_EXPIRE_TIME
     *
     * @return the value of OPERATOR.PASSWD_EXPIRE_TIME
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    public Date getPasswdExpireTime() {
        return passwdExpireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OPERATOR.PASSWD_EXPIRE_TIME
     *
     * @param passwdExpireTime the value for OPERATOR.PASSWD_EXPIRE_TIME
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    public void setPasswdExpireTime(Date passwdExpireTime) {
        this.passwdExpireTime = passwdExpireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OPERATOR.PASSWD_EFFECT_TIME
     *
     * @return the value of OPERATOR.PASSWD_EFFECT_TIME
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    public Date getPasswdEffectTime() {
        return passwdEffectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OPERATOR.PASSWD_EFFECT_TIME
     *
     * @param passwdEffectTime the value for OPERATOR.PASSWD_EFFECT_TIME
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    public void setPasswdEffectTime(Date passwdEffectTime) {
        this.passwdEffectTime = passwdEffectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OPERATOR.TRY_TIMES
     *
     * @return the value of OPERATOR.TRY_TIMES
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    public Integer getTryTimes() {
        return tryTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OPERATOR.TRY_TIMES
     *
     * @param tryTimes the value for OPERATOR.TRY_TIMES
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    public void setTryTimes(Integer tryTimes) {
        this.tryTimes = tryTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OPERATOR.ORG_CODE
     *
     * @return the value of OPERATOR.ORG_CODE
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OPERATOR.ORG_CODE
     *
     * @param orgCode the value for OPERATOR.ORG_CODE
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OPERATOR.STAFF_NO
     *
     * @return the value of OPERATOR.STAFF_NO
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    public String getStaffNo() {
        return staffNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OPERATOR.STAFF_NO
     *
     * @param staffNo the value for OPERATOR.STAFF_NO
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    public void setStaffNo(String staffNo) {
        this.staffNo = staffNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OPERATOR.PHONE_NO
     *
     * @return the value of OPERATOR.PHONE_NO
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    public String getPhoneNo() {
        return phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OPERATOR.PHONE_NO
     *
     * @param phoneNo the value for OPERATOR.PHONE_NO
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OPERATOR.CUSTOMER_NO
     *
     * @return the value of OPERATOR.CUSTOMER_NO
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    public String getCustomerNo() {
        return customerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OPERATOR.CUSTOMER_NO
     *
     * @param customerNo the value for OPERATOR.CUSTOMER_NO
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    public void setCustomerNo(String customerNo) {
        this.customerNo = customerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OPERATOR.CUSTOMER_TEL
     *
     * @return the value of OPERATOR.CUSTOMER_TEL
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    public String getCustomerTel() {
        return customerTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OPERATOR.CUSTOMER_TEL
     *
     * @param customerTel the value for OPERATOR.CUSTOMER_TEL
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    public void setCustomerTel(String customerTel) {
        this.customerTel = customerTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OPERATOR.AGENT_NO
     *
     * @return the value of OPERATOR.AGENT_NO
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    public String getAgentNo() {
        return agentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OPERATOR.AGENT_NO
     *
     * @param agentNo the value for OPERATOR.AGENT_NO
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    public void setAgentNo(String agentNo) {
        this.agentNo = agentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OPERATOR.SECOND_AGENT_ID
     *
     * @return the value of OPERATOR.SECOND_AGENT_ID
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    public String getSecondAgentId() {
        return secondAgentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OPERATOR.SECOND_AGENT_ID
     *
     * @param secondAgentId the value for OPERATOR.SECOND_AGENT_ID
     *
     * @mbggenerated Fri Apr 21 10:25:13 CST 2017
     */
    public void setSecondAgentId(String secondAgentId) {
        this.secondAgentId = secondAgentId;
    }
}